# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0004_auto_20170214_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='style',
            field=models.CharField(choices=[('Cerulean', 'Cerulean'), ('Darkly', 'Darkly'), ('Superhero', 'Superhero'), ('Cosmo', 'Cosmo'), ('Slate', 'Slate')], default='Cerulean', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
