# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0005_auto_20170219_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='djangoBlog.Image'),
        ),
    ]
