# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBlog', '0006_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
